import React from 'react';
import './Footer.css'

const Footer = () => {
    return (
        <footer className="App-footer">
            <p>This websyte is generated by GatsbyJS.</p>
        </footer>
    );
};

export default Footer;